services:
  telegram-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=<replace with your token>
      - OLLAMA_API_ENDPOINT=http://ollama-server:11434

  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama